export enum PokemonType {
  All = 'ALL',
  Normal = 'Normal',
  Fighting = 'FIGHTING',
  Flying = 'FLYING',
  Poison = 'POISON',
  Ground = 'GROUND',
  Rock = 'ROCK',
  Bug = 'BUG',
  Ghost = 'GHOST',
  Steel = 'STEEL',
  Fire = 'FIRE',
  Water = 'WATER',
  Grass = 'GRASS',
  Electric = 'ELECTRIC',
  Psychic = 'PSYHIC',
  Ice = 'ICE',
  Dragon = 'DRAGON',
  Dark = 'DARK',
  Fairy = 'FAIRY',
  Unknown = 'UNKNOWN',
  Shadow = 'SHADOW',
}
